# ==============================
# BASE IMAGE
# ==============================
FROM python:3.11.13-slim
WORKDIR /app

# ==============================
# INSTALL DEPENDENCIES
# ==============================
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl unzip && \
    rm -rf /var/lib/apt/lists/*

# ==============================
# COPY PROJECT FILES
# ==============================
COPY . .

# ==============================
# NLTK
# ==============================
ENV NLTK_DATA=/usr/local/nltk_data
RUN mkdir -p ${NLTK_DATA}

COPY nltk_data ${NLTK_DATA}

RUN find ${NLTK_DATA} -name "*.zip" -exec sh -c 'unzip -q "{}" -d "$(dirname "{}")"' \; && \
    find ${NLTK_DATA} -name "*.zip" -delete

# ==============================
# EXPOSE PORT
# Flask will run on :5000
# ==============================
EXPOSE 5000

# ==============================
# DEFAULT COMMAND
# ==============================
RUN apt-get update && apt-get install -y supervisor \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/log/supervisor

# Copy supervisord config
COPY supervisord_flask.conf /etc/supervisor/conf.d/supervisord_flask.conf

# Start supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord_flask.conf"]