# ==============================
# BASE IMAGE
# ==============================
FROM python:3.11.13-slim
WORKDIR /app

# ==============================
# INSTALL DEPENDENCIES
# ==============================
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ==============================
# COPY PROJECT FILES
# ==============================
COPY . .

# ==============================
# EXPOSE PORT
# Streamlit will run on :8000
# ==============================
EXPOSE 8000

# ==============================
# DEFAULT COMMAND
# ==============================
# ==============================
RUN apt-get update && apt-get install -y supervisor \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/log/supervisor

# Copy supervisord config
COPY supervisord_streamlit.conf /etc/supervisor/conf.d/supervisord_streamlit.conf

# Start supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord_streamlit.conf"]