"""Correção do nome da coluna data de nascimento

Revision ID: 3f806c2bf76e
Revises: f1081516551c
Create Date: 2025-09-02 11:51:33.550303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f806c2bf76e'
down_revision: Union[str, Sequence[str], None] = 'f1081516551c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('birthdate', sa.Date(), nullable=True))
    op.drop_column('usuarios', 'birthdata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('birthdata', sa.DATE(), nullable=True))
    op.drop_column('usuarios', 'birthdate')
    # ### end Alembic commands ###
