"""Adição de data de nascimento na tabela usuarios

Revision ID: f1081516551c
Revises: 6aee55335cb0
Create Date: 2025-09-02 11:50:08.817130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1081516551c'
down_revision: Union[str, Sequence[str], None] = '6aee55335cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('birthdata', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'birthdata')
    # ### end Alembic commands ###
